### ISSUE TITLE
Where can I find the memory cost model implementation in the project?

### ISSUE THREAD

**Issue by robotsp** [awslabs/optimizing-multitask-training-through-dynamic-pipelines#1]
@hyandell @chenyu-jiang @mattsb42-aws 

Thanks!

**Comment by chenyu-jiang** [comment]
The memory (and execution time) cost model is implemented here: https://github.com/awslabs/optimizing-multitask-training-through-dynamic-pipelines/blob/705cf383e83e47a4b936619c230c681585835380/dynapipe/data_opt/cost_models.py#L26

You can follow the comments in `ProfileBasedCostModel` to see how a cost model can be generated.
